# Generated by Django 4.2.2 on 2024-04-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipants',
            name='room_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
