# Generated by Django 4.2.2 on 2024-04-10 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_roomparticipants_room_name_rooms_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='type',
            new_name='isGroupChat',
        ),
    ]
